version: '3.7'

services:
  sw-ui:
    image: swaggerapi/swagger-ui
    tty: true
    container_name: sw_ui
    ports:
      - 1110:8080
    environment:
      - SWAGGER_JSON=/tmp/swagger.yaml
    volumes:
      - ./swagger.yaml:/tmp/swagger.yaml
  db:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: tutorial_mysql
    tty: true
    ports:
      - 16002:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      # - ./db/init:/docker-entrypoint-initdb.d
      - tutorial-db-volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=tutorial
      - MYSQL_ROOT_PASSWORD=password

volumes:
  tutorial-db-volume: