version: "3.7"

services:
  sw-ui:
    image: swaggerapi/swagger-ui
    tty: true
    container_name: sw_ui
    ports:
      - 1110:8080
    environment:
      - SWAGGER_JSON=/tmp/swagger.yaml
    volumes:
      - ./swagger.yaml:/tmp/swagger.yaml
  db:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: tutorial_mysql
    tty: true
    ports:
      - 16002:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      # - ./db/init:/docker-entrypoint-initdb.d
      - gacha-db-volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=gacha_db
      - MYSQL_ROOT_PASSWORD=password
  prd:
    build:
      context: .
      dockerfile: Dockerfile.prd
    image: gacha_prd:latest
    container_name: gacha_prd
    tty: true
    env_file:
      - .env.prd
    ports:
      - 16003:8080

volumes:
  gacha-db-volume:
